### ISSUE TITLE
tabs VS spaces

### ISSUE THREAD

**Issue by maxkoryukov** [route4me/route4me-python-sdk#1]
Hello!

PEP8 forces to use 4 spaces for **indentation**

But we could use `TAB` (for indentation, not for spacing at end of line), and tune IDE's (and text editors) to represent `TAB` as 4 spaces.

What you think about this?

**Comment by juanroute4me** [comment]
I always use 4 spaces as indentation and set my IDES to represent TAB as 4 spaces. I try to keep my PEP8. We could use pylint in the projects if you want.

**Comment by maxkoryukov** [comment]
ok. you are the author ;) let  me configure **my** IDE (actually, Sublime), to conform existing conventions;)

about PYLINT: I am going to add [flake8](https://pypi.python.org/pypi/flake8) to the python-toolchain (at least on Travis and as instructions to the readme)

Shortly: `flake8` - it is an multi-tool (pep8 + pyflake + pylint + ??). One tool instead of 3
