### ISSUE TITLE
Visualising  the JSON Output for Optimised Route via a Graph/Map using Python

### ISSUE THREAD

**Issue by JayDS22** [route4me/route4me-python-sdk#17]
Hello Team,

I am stuck at a point where I need to use the Generated JSON output for Optimised and Non-Optimised routes, to generate a visual for show casing the same in our reports using Python. Could you please guide us with the same?

Awaiting your response

Reference Output :
<img width="1440" alt="Screenshot 2022-04-25 at 3 16 54 PM" src="https://user-images.githubusercontent.com/91157708/165065409-4f14da9e-b874-4aab-88a8-36c4431fcbb5.png">

**Comment by juanroute4me** [comment]
@JayDS22 Can you create a ticket in support to help you with this.
